export default {
  FETCH_USERS: 'FETCH_USERS',
  FETCH_ONLINE: 'FETCH_ONLINE',
  FETCH_MESSAGES: 'FETCH_MESSAGES',
  SEND_MESSAGE: 'SEND_MESSAGE',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  MUTE_USER: 'MUTE_USER',
  BAN_USER: 'BAN_USER',
  FETCH_USER_LIST: 'FETCH_USER_LIST',
  FETCH_MUTE_USER: 'FETCH_MUTE_USER',
  UNMUTE_USER: 'UNMUTE_USER',
  FETCH_UNMUTE_USER: 'FETCH_UNMUTE_USER'
};
